# Generated by Django 5.1.7 on 2025-03-14 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_complete',
        ),
    ]
